rootUrl: 'https://ascensus.weareenvoy.net'
gridUrl: 'https://jonlee567:z7sR4zHk6W2AX37u28tr@hub-cloud.browserstack.com/wd/hub'
tolerance: 2.3
compositeImage: true
browsers:
  highsierra-safari-desktop-viewport:
    windowSize: 1280x1024
    desiredCapabilities:
      os : OS X
      os_version : High Sierra
      browserName : Safari
      browser_version : 11.0
# Defines the set of tests to run. Command line option needs to specify '--set <set name>'
sets:
  Safari:
    files:
      - gemini/suites/ascensus/*Desktop.js
    browsers:
      - highsierra-safari-desktop-viewport
system:
  projectRoot: ../../
  plugins:
    html-reporter/gemini:
      enabled: true
      scaleImages: true
      path: './gemini-reports/ascensus/safari'
  ctx: {
    foo: 'bar'
  }