rootUrl: 'https://ascensus.weareenvoy.net'
gridUrl: 'https://jonlee567:z7sR4zHk6W2AX37u28tr@hub-cloud.browserstack.com/wd/hub'
tolerance: 2.3
compositeImage: true
browsers:
  win-ff-desktop-viewport:
    windowSize: 1280x1024
    desiredCapabilities:
      os : Windows
      os_version : 10
      browserName : Firefox
      browser_version : 47.0
      browserstack.selenium_version: 2.53.1
  highsierra-ff-desktop-viewport:
    windowSize: 1280x1024
    desiredCapabilities:
      os : OS X
      os_version : High Sierra
      browserName : Firefox
      browser_version : 47.0
      browserstack.selenium_version: 2.53.1
# Defines the set of tests to run. Command line option needs to specify '--set <set name>'
sets:
  Firefox:
    files:
      - gemini/suites/ascensus/*Desktop.js
    browsers:
      - win-ff-desktop-viewport
      - highsierra-ff-desktop-viewport
system:
  projectRoot: ../../
  plugins:
    html-reporter/gemini:
      enabled: true
      path: './gemini-reports/ascensus/firefox'
  ctx: {
    foo: 'bar'
  }