rootUrl: 'https://ascensus.weareenvoy.net'
gridUrl: 'https://jonlee567:z7sR4zHk6W2AX37u28tr@hub-cloud.browserstack.com/wd/hub'
tolerance: 2.3
compositeImage: true
browsers:
  win-chrome-desktop-viewport:
    windowSize: 1280x1024
    desiredCapabilities:
      os : Windows
      os_version : 10
      browserName : Chrome
      browser_version : 62.0
  highsierra-chrome-desktop-viewport:
    windowSize: 1280x1024
    desiredCapabilities:
      os : OS X
      os_version : High Sierra
      browserName : Chrome
      browser_version : 65.0
      browserstack.selenium_version : 3.5.2
# Defines the set of tests to run. Command line option needs to specify '--set <set name>'
sets:
  Chrome:
    files:
      - gemini/suites/ascensus/*Desktop.js
    browsers:
      - highsierra-chrome-desktop-viewport
      - win-chrome-desktop-viewport
system:
  projectRoot: ../../
  plugins:
    html-reporter/gemini:
      enabled: true
      scaleImages: true
      path: './gemini-reports/ascensus/chrome'
  ctx: {
    foo: 'bar'
  }