rootUrl: 'https://spiritu-landing.weareenvoy.net'
gridUrl: 'http://127.0.0.1:4444/wd/hub'  #'https://jonlee567:z7sR4zHk6W2AX37u28tr@hub-cloud.browserstack.com/wd/hub'
tolerance: 2.3
compositeImage: true
screenshotDelay: 3000   # With composite image true, when gemini needs to scroll to capture elements it will wait 2 seconds between each capture.
screenshotsDir: ./gemini/screens/spiritu
browsers:
  chrome-default:
    desiredCapabilities:
      browserName: chrome
  chrome-default-mob-viewport:
    windowSize: 425x1024
    desiredCapabilities:
      browserName: chrome
  win-chrome-desktop-viewport:
    windowSize: 1280x1024
    desiredCapabilities:
      os : Windows
      os_version : 10
      browserName : Chrome
      browser_version : 62.0
  win-ff-desktop-viewport:
    windowSize: 1280x1024
    desiredCapabilities:
      os : Windows
      os_version : 10
      browserName : Firefox
      browser_version : 47.0
      browserstack.selenium_version: 2.53.1
  win-ie-desktop-viewport:
    windowSize: 1280x1024
    desiredCapabilities:
      os : Windows
      os_version : 10
      browserName : IE
      browser_version : 11.0
  win-edge-desktop-viewport:
    windowSize: 1280x1024
    desiredCapabilities:
      os : Windows
      os_version : 10
      browserName : Edge
      browser_version : 16.0
  highsierra-safari-desktop-viewport:
    windowSize: 1280x1024
    desiredCapabilities:
      os : OS X
      os_version : High Sierra
      browserName : Safari
      browser_version : 11.0
  highsierra-chrome-desktop-viewport:
    windowSize: 1280x1024
    desiredCapabilities:
      os : OS X
      os_version : High Sierra
      browserName : Chrome
      browser_version : 65.0
      browserstack.selenium_version : 3.5.2
  highsierra-ff-desktop-viewport:
    windowSize: 1280x1024
    desiredCapabilities:
      os : OS X
      os_version : High Sierra
      browserName : Firefox
      browser_version : 47.0
      browserstack.selenium_version: 2.53.1
# Defines the set of tests to run. Command line option needs to specify '--set <set name>'
sets:
  safari:
    files:
      - gemini/suites/spiritu/*.js
    browsers:
      - highsierra-safari-desktop-viewport
  ie-edge:
    files:
      - gemini/suites/spiritu/*.js
    browsers:
      - win-ie-desktop-viewport
      - win-edge-desktop-viewport
  firefox:
    files:
      - gemini/suites/spiritu/*.js
    browsers:
      - win-ff-desktop-viewport
      - highsierra-ff-desktop-viewport
  chrome:
    files:
      - gemini/suites/spiritu/*.js
    browsers:
      - highsierra-chrome-desktop-viewport
      - win-chrome-desktop-viewport
  chrome-default:
    files:
      - gemini/suites/spiritu/*.js
    browsers:
      - chrome-default
  chrome-mob:
    files:
      - gemini/suites/spiritu/*.js
    browsers:
      - chrome-default-mob-viewport
  landing-chrome:
    files:
      - gemini/suites/spiritu/landing-page-test.js
    browsers:
      - chrome-default
system:
  projectRoot: ../../
  plugins:
    html-reporter/gemini:
      enabled: true
      scaleImages: true
      path: './gemini-reports/spiritu'
  ctx: {
    foo: 'bar'
  }