rootUrl: 'https://inscape.weareenvoy.net'
gridUrl: 'http://127.0.0.1:4444/wd/hub'
tolerance: 2.3
compositeImage: true
browsers:
  chrome-desktop-viewport:
    desiredCapabilities:
      browserName: chrome
    windowSize: 1600x1080
  chrome-mobile-viewport:
    desiredCapabilities:
      browserName: chrome
    windowSize: 425x667  # Viewport width < 425 renders inconsistent images due to horizontal scroll.
  chrome-tablet-viewport:
    desiredCapabilities:
      browserName: chrome
    windowSize: 768x1024
  # BROKEN: Latest ff version 57 not compatible with latest selenium server 3.8.1
  # firefox:
  #   calibrate: true
  #   desiredCapabilities:
  #     browserName: firefox
  # safari:
  #   desiredCapabilities:
  #     browserName: safari
# Defines the set of tests to run. Command line option needs to specify '--set desktop'
sets:
  desktopViewport:
    files:
      - gemini/suites/inscape/inscape.js
    browsers:
      - chrome-desktop-viewport
  mobileViewport:
    files:
      - gemini/suites/inscape/inscape.js
    browsers:
      - chrome-mobile-viewport
  tabletViewport:
    files:
      - gemini/suites/inscape/inscape.js
    browsers:
      - chrome-tablet-viewport
system:
  projectRoot: ../../
  plugins:
    'html-reporter':
      enabled: true
      path: './gemini-reports/inscape'
  ctx: {
    foo: 'bar'
  }